---
title: "scraping"
author: "Emily Halford"
date: "4/11/2021"
output: html_document
---

## Load libraries

The rvest package is used for the actual web-scraping, and the tidyverse allows us to manipulate/clean the scraped table. 

```{r}
library(tidyverse)
library(rvest)
```

## Extracting the table

```{r}

## Read and identify table objects from the webpage of interest:

url = "https://en.wikipedia.org/wiki/Houston"
houston_html = read_html(url)
houston_html

houston_html %>% 
  html_nodes(css = "table")

## Pull out the table we're interested in:

pop_table = 
  houston_html %>% 
  html_nodes(css = "table") %>% 
  nth(4) %>% 
  html_table(fill = TRUE) 

## Clean the table:

colnames(pop_table) = c("year", "population", "blank", "percent_change")

pop_table = pop_table[2:19, ]

pop_table = 
  pop_table %>% 
  select(-blank) %>% 
  mutate(
    percent_change = str_replace(percent_change, "%", ""),
    percent_change = str_replace(percent_change, "—", ""),
    year = str_replace(year, "\\(est.\\)", ""),
    population = str_replace_all(population, ",", ""),
    year = lubridate::ymd(year, truncated = 2L),
    population = as.numeric(population),
    percent_change = as.numeric(percent_change)
  )

```


